<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>VGModAPI</AssemblyName>
    <RootNamespace>VGModAPI</RootNamespace>
    <DefineConstants>$(DefineConstants);VG_WORLD_QUALIFICATION</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../VGModAPI/**/*.cs" Exclude="../../VGModAPI/obj/**;../../VGModAPI/bin/**" />
    <ProjectReference Include="../../VGModAPI.Core/VGModAPI.Core.csproj" />
    <Reference Include="BepInEx"><HintPath>../../VGModAPI/lib/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../../VGModAPI/lib/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>../../VGModAPI/lib/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../VGModAPI/lib/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>../../VGModAPI/lib/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>../../VGModAPI/lib/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>../../VGModAPI/lib/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.InputSystem"><HintPath>../../VGModAPI/lib/Unity.InputSystem.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <Import Project="../PluginVersion.targets" />
</Project>
