<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>VGModAPI.UpdateParticipant</RootNamespace>
    <ExampleVersion Condition="'$(ExampleVersion)' == ''">1.0.0</ExampleVersion>
    <Version>$(ExampleVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../VGModAPI.Abstractions/VGModAPI.Abstractions.csproj" Private="false" />
    <Reference Include="BepInEx"><HintPath>../../VGModAPI/lib/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>../../VGModAPI/lib/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../VGModAPI/lib/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <Import Project="../../tools/PluginVersion.targets" />
</Project>
