namespace VGModAPI.Core.Integration;

/// <summary>Inspected serialization/construction boundaries. Declaring bindings does not install a world capability.</summary>
internal static class WorldNativeBindings
{
    private const string Poi = "Source.Galaxy.MapPointOfInterest", Batch = "System.Collections.Generic.List`1<Source.Data.AbstractUnitData>", Faction = "Source.Galaxy.Faction";
    private const string Gameplay = "System.Nullable`1<Source.Util.GameplayType>", Rank = "System.Nullable`1<Behaviour.Unit.UnitRank>", Vector = "System.Nullable`1<UnityEngine.Vector2>";
    internal static readonly MethodBinding[] Methods =
    {
        new("worldRecall", BindingCatalog.File, "Recall", false, "LightJson.JsonObject"),
        new("worldPoiRead", "Source.Galaxy.MapPointOfInterest", "FromJson", true, "Source.Galaxy.MapPointOfInterest", "LightJson.JsonValue"),
        new("worldSystemRead", "Source.Galaxy.SystemMapData", "FromJson", true, "Source.Galaxy.SystemMapData", "Source.Galaxy.SectorMapData", "LightJson.JsonValue"),
        new("worldSnapshot", BindingCatalog.Save, "SaveCurrentState", true, "LightJson.JsonObject"),
        new("worldStore", BindingCatalog.Save, "Store", true, "System.Void", "LightJson.JsonObject", "System.String", "Source.Util.SaveGameFormat", "System.Int32"),
        new("worldElementWrite", "Source.Galaxy.MapElement", "ToJson", false, "LightJson.JsonValue"),
        new("worldRemove", "Source.Galaxy.SystemMapData", "RemovePointOfInterest", false, "System.Void", "Source.Galaxy.MapPointOfInterest"),
        new("worldActorSetData", "Behaviour.Unit.AbstractUnit", "SetData", false, "System.Void", "Source.Data.AbstractUnitData", "System.Boolean", "System.Boolean"),
        new("worldShipSetData", "Behaviour.Unit.SpaceShip", "SetData", false, "System.Void", "Source.Data.AbstractUnitData", "System.Boolean", "System.Boolean"),
        new("worldActorModules", "Behaviour.Unit.AbstractUnit", "InitModules", false, "System.Void"),
        new("worldActorDamage", "Behaviour.Unit.AbstractUnit", "TakeDamage", false, "System.Void", "Behaviour.Weapons.DamageData"),
        new("worldShipDamage", "Behaviour.Unit.SpaceShip", "TakeDamage", false, "System.Void", "Behaviour.Weapons.DamageData"),
        new("worldActorRoutineAuto", "Behaviour.Unit.AbstractUnit", "StartAutoActions", false, "System.Collections.IEnumerator"),
        new("worldActorRoutineRemains", "Behaviour.Unit.AbstractUnit", "CreateRemainsWithPotentialSalvage", false, "System.Collections.IEnumerator"),
        new("worldActorRoutineImpulse", "Behaviour.Unit.AbstractUnit", "HandleImpulse", false, "System.Collections.IEnumerator", "UnityEngine.Vector2", "System.Single", "System.Single"),
        new("worldActorRoutineCollision", "Behaviour.Unit.AbstractUnit", "RestoreCollision", false, "System.Collections.IEnumerator", "UnityEngine.Collider2D", "UnityEngine.Collider2D"),
        new("worldActorRoutineTravel", "Behaviour.Unit.SpaceShip", "PrepareForInSystemTravel", false, "System.Collections.IEnumerator", "UnityEngine.Vector2", "System.Boolean"),
        new("worldActorRoutineDrones", "Behaviour.Unit.SpaceShip", "WaitForDrones", false, "System.Collections.IEnumerator", "System.Boolean"),
        new("worldActorRoutineExit", "Behaviour.Unit.SpaceShip", "ExitProtocol", false, "System.Collections.IEnumerator", "UnityEngine.Vector2"),
        new("worldActorRoutineLand", "Behaviour.Unit.SpaceShip", "LandNpcAtPoi", false, "System.Collections.IEnumerator", "UnityEngine.Vector2"),
        new("worldActorRoutineDockDrones", "Behaviour.Unit.SpaceShip", "WaitForAllDronesToDock", false, "System.Collections.IEnumerator"),
        new("worldActorRoutineDockFighters", "Behaviour.Unit.SpaceShip", "WaitForAllFightersToDock", false, "System.Collections.IEnumerator"),
        new("worldActorCollisionEnter", "Behaviour.Unit.AbstractUnit", "OnCollisionEnter2D", false, "System.Void", "UnityEngine.Collision2D"),
        new("worldActorCollisionStay", "Behaviour.Unit.AbstractUnit", "OnCollisionStay2D", false, "System.Void", "UnityEngine.Collision2D"),
        new("worldPersistableStart", "Behaviour.Util.PersistableUpdater", "Start", false, "System.Void"),
        new("worldPersistableUpdate", "Behaviour.Util.PersistableUpdater", "Update", false, "System.Void"),
        new("worldEmptyPirateTurrets", Poi, "AddPirateTurrets", false, Batch, "System.Int32", "SeededRandom", Faction, "System.Boolean"),
        new("worldEmptyGuards", Poi, "AddGuards", false, Batch, Batch, "SeededRandom", "System.Boolean"),
        new("worldEmptyBudgetGuards", Poi, "AddGuardsFromUnitPayload", false, Batch, "System.Single", Gameplay, Faction, "System.Int32", "System.Int32", "System.Int32", "System.Int32", Rank, Vector, Vector, "System.String", "System.Boolean"),
        new("worldEmptyFixedGuards", Poi, "AddGuardsFromFixedPayload", false, Batch, "System.String", "System.Int32", Faction, Gameplay, "Behaviour.Unit.UnitRank", "System.Nullable`1<System.Int32>", "System.String"),
        new("worldEmptyGuardBatch", Poi, "AddGuardBatch", false, Batch, Batch, "System.Int32", "SeededRandom", "System.Boolean"),
        new("worldEmptyFixedPayload", Poi, "CreateFixedPayload", false, Batch, "System.String", "System.Int32", Faction, Gameplay, "Behaviour.Unit.UnitRank", "System.Nullable`1<System.Int32>", "SeededRandom", "System.Boolean"),
        new("worldEmptyBudgetPayload", Poi, "CreateUnitPayload", false, Batch, "System.Single", Gameplay, Faction, "System.Int32", "System.Int32", "System.Int32", "System.Int32", Rank, "SeededRandom"),
        new("worldEmptyTurretPayload", Poi, "CreateTurretPayload", false, Batch, "System.Int32", Faction, "SeededRandom"),
        new("worldEmptyHazard", Poi, "CreateHazardData", false, "Source.Hazard.HazardData"),
        new("worldEmptyTypedHazard", Poi, "CreateHazardData", false, "Source.Hazard.HazardData", "Behaviour.Hazard.HazardName", "Source.Combat.DamageType"),
        new("worldEmptyCargo", Poi, "AddCargoContainers", false, "System.Void", "UnityEngine.Vector2", "System.Int32", "System.Single"),
        new("worldEmptyAsteroidData", Poi, "SetAsteroidFieldData", false, "System.Void", "Source.Mining.AsteroidFieldData", "System.Int32"),
        new("worldEmptyInitializeAsteroids", Poi, "InitializeAsteroids", false, "System.Void", "System.Boolean", "System.Boolean"),
        new("worldEmptyGeneratePersistables", Poi, "GeneratePoiPersistables", false, "System.Void", Faction, "System.Boolean"),
        new("worldEmptyDungeon", Poi, "BuildDungeonLocationData", false, "Source.Data.Persistable.DungeonLocationData", "Source.Dungeon.DungeonType", Faction, "SeededRandom", "System.Boolean"),
        new("worldEmptyDungeonPresence", Poi, "InitializeDungeonPresence", false, "System.Void", "Source.Data.Persistable.DungeonLocationData", "SeededRandom"),
        new("worldSalvageReset", "Source.Galaxy.MapPointOfInterest", "ResetStaleSalvageContent", false, "System.Void"),
        new("worldSalvageAdd", "Source.Galaxy.MapPointOfInterest", "AddSalvageFromDescriptor", false, "UnityEngine.GameObject", "Source.Galaxy.SalvageGenerationDescriptor"),
        new("worldSalvageSlot", "Source.Galaxy.MapPointOfInterest", "GenerateSalvageSlot", false, "UnityEngine.GameObject", "System.Int32"),
        new("worldSalvageDescriptor", "Source.Galaxy.StandardSalvageDescriptor", "Generate", false, "Source.Data.Persistable.SalvageData", "Source.Galaxy.MapPointOfInterest", "SeededRandom"),
        new("worldBudgetBuilder", "Behaviour.Equipment.Builder.EquipmentBuilder", "CreateItemType", false, "Behaviour.Item.InventoryItemType", "Source.Item.Rarity", "System.Int32", "System.Boolean", "System.String", "System.Boolean", "System.Boolean"),
        new("worldActorAwake", "Behaviour.Unit.AbstractUnit", "Awake", false, "System.Void"),
        new("worldActorStart", "Behaviour.Unit.AbstractUnit", "Start", false, "System.Void"),
        new("worldActorUpdate", "Behaviour.Unit.AbstractUnit", "Update", false, "System.Void"),
        new("worldActorPhysics", "Behaviour.Unit.AbstractUnit", "FixedUpdate", false, "System.Void"),
        new("worldShipStart", "Behaviour.Unit.SpaceShip", "Start", false, "System.Void"),
        new("worldShipUpdate", "Behaviour.Unit.SpaceShip", "Update", false, "System.Void"),
        new("worldPoiAddPayload", "Source.Galaxy.MapPointOfInterest", "AddPayload", false, "System.Void", "Source.Galaxy.MapTriggeredPayload"),
        new("worldAddTriggered", "Source.Galaxy.MapPointOfInterest", "AddTriggeredSpawn", false, "System.Collections.Generic.List`1<Source.Data.AbstractUnitData>", "System.Collections.Generic.List`1<Source.Data.AbstractUnitData>", "System.Single", "System.Int32", "System.Boolean", "System.Boolean", "SeededRandom", "Source.Galaxy.UnitGenerationDescriptor", "System.Nullable`1<System.Int32>"),
        new("worldAddBudgetPayload", "Source.Galaxy.MapPointOfInterest", "AddTriggeredSpawnFromUnitPayload", false, "System.Collections.Generic.List`1<Source.Data.AbstractUnitData>", "System.Single", "System.Single", "System.Nullable`1<Source.Util.GameplayType>", "Source.Galaxy.Faction", "System.Int32", "System.Int32", "System.Int32", "System.Int32", "System.Nullable`1<Behaviour.Unit.UnitRank>", "System.Int32", "System.Boolean", "System.Boolean", "System.String", "System.Nullable`1<UnityEngine.Vector2>", "System.Nullable`1<UnityEngine.Vector2>", "System.String", "System.Boolean", "System.Boolean"),
        new("worldAddFixedPayload", "Source.Galaxy.MapPointOfInterest", "AddTriggeredSpawnFromFixedPayload", false, "System.Collections.Generic.List`1<Source.Data.AbstractUnitData>", "System.Single", "System.String", "System.Int32", "Source.Galaxy.Faction", "System.Nullable`1<Source.Util.GameplayType>", "Behaviour.Unit.UnitRank", "System.Nullable`1<System.Int32>", "System.Int32", "System.Boolean", "System.Boolean", "System.String", "System.Single", "System.String", "System.Boolean"),
        new("worldPoiAddPersistable", "Source.Galaxy.MapPointOfInterest", "AddPersistable", false, "UnityEngine.GameObject", "Source.Data.Persistable.PersistableData"),
        new("worldPoiRemovePersistable", "Source.Galaxy.MapPointOfInterest", "RemovePersistable", false, "System.Void", "Source.Data.Persistable.PersistableData"),
        new("worldPoiAddUnit", "Source.Galaxy.MapPointOfInterest", "AddUnit", false, "Behaviour.Unit.AbstractUnit", "Source.Data.AbstractUnitData", "System.String", "System.Boolean"),
        new("worldPoiRemoveUnit", "Source.Galaxy.MapPointOfInterest", "RemoveUnit", false, "System.Void", "Source.Data.AbstractUnitData"),
        new("worldPayloadUpdate", "Source.Galaxy.MapTriggeredPayload", "Update", false, "System.Boolean", "System.Single"),
        new("worldPayloadTrigger", "Source.Galaxy.MapTriggeredPayload", "TriggerPayload", false, "System.Void"),
        new("worldPayloadSpawn", "Source.Galaxy.MapTriggeredPayload", "SpawnUnit", false, "System.Void", "Source.Data.AbstractUnitData"),
        new("worldRegenerateGuards", "Source.Galaxy.MapPointOfInterest", "RegenerateGuardUnits", true, "System.Void", "Source.Galaxy.MapPointOfInterest"),
        new("worldRegenerateCargo", "Source.Galaxy.MapPointOfInterest", "RegenerateCargoContainers", true, "System.Void", "Source.Galaxy.MapPointOfInterest"),
        new("worldRegenerateSalvage", "Source.Galaxy.MapPointOfInterest", "RegenerateSalvage", true, "System.Void", "Source.Galaxy.MapPointOfInterest"),
        new("worldRegenerateAsteroids", "Source.Galaxy.MapPointOfInterest", "RegenerateAsteroidField", false, "System.Void"),
        new("worldRebuildStation", "Source.Galaxy.MapPointOfInterest", "RebuildStationBuilding", false, "System.Void"),
        new("worldJumpgateWave", "Source.Galaxy.MapPointOfInterest", "EnsureJumpgatePassWave", false, "System.Void"),
        new("worldDeferGeneration", "Source.Galaxy.MapPointOfInterest", "MarkDeferredContentGeneration", false, "System.Void"),
        new("worldGenerate", "Source.Galaxy.MapPointOfInterest", "EnsureContentGenerated", false, "System.Void"),
        new("worldCancelTravel", BindingCatalog.TravelManager, "CancelTravel", false, "System.Boolean", "System.Nullable`1<UnityEngine.Vector2>"),
        new("worldWaitUnload", BindingCatalog.TravelManager, "WaitForSceneUnload", false, "System.Void", "System.String"),
        new("worldCheckLocalScene", BindingCatalog.TravelManager, "CheckLocalPoiStatus", false, "System.Void"),
        new("worldUnloadScene", BindingCatalog.TravelManager, "UnloadCurrentScene", false, "System.Void"),
        new("worldTravelChild", BindingCatalog.TravelManager, "RunAndSignal", false, "System.Collections.IEnumerator", "System.Collections.IEnumerator", "System.Action"),
        new("worldStartTravel", BindingCatalog.TravelManager, "StartTravel", false, "System.Collections.IEnumerator", "Source.Galaxy.MapPointOfInterest"),
        new("worldNextWaypoint", BindingCatalog.TravelManager, "TravelToNextWaypoint", false, "System.Void"),
        new("worldBaseAwake", "Behaviour.Managers.BasePoiManager", "Awake", false, "System.Void"),
        new("worldCombatAwake", "Behaviour.Combat.CombatManager", "Awake", false, "System.Void"),
        new("worldStoreLastX", "Behaviour.Managers.BasePoiManager", "StoreLastX", false, "System.Void"),
        new("worldStorePosition", "Behaviour.Managers.BasePoiManager", "StorePositionData", false, "System.Void"),
        new("worldIncomingReinforcements", "Behaviour.Managers.BasePoiManager", "CheckForIncomingReinforcements", false, "System.Void"),
        new("worldCreateSecurityPatrol", "Behaviour.Managers.BasePoiManager", "CreateSecurityPatrol", false, "System.Void"),
        new("worldManagerStart", "Behaviour.Managers.BasePoiManager", "Start", false, "System.Void"),
        new("worldManagerUpdate", "Behaviour.Managers.BasePoiManager", "Update", false, "System.Void"),
        new("worldSecurityPatrol", "Behaviour.Managers.BasePoiManager", "EvaluateSecurityPatrol", false, "System.Void"),
        new("worldManagerInit", "Behaviour.Managers.BasePoiManager", "Init", false, "System.Collections.IEnumerator"),
        new("worldInitializePoi", "Behaviour.Managers.BasePoiManager", "InitializePoi", false, "System.Collections.IEnumerator"),
        new("worldInitializationComplete", "Behaviour.Managers.BasePoiManager", "InitializationComplete", false, "System.Collections.IEnumerator"),
        new("worldBaseArrival", "Behaviour.Managers.BasePoiManager", "SpaceshipHasArrived", false, "System.Void"),
        new("worldCombatArrival", "Behaviour.Combat.CombatManager", "SpaceshipHasArrived", false, "System.Void"),
        new("worldSpawnPersistable", "Behaviour.Managers.BasePoiManager", "AddToWorld", false, "UnityEngine.GameObject", "Source.Data.Persistable.PersistableData"),
        new("worldSpawnUnit", "Behaviour.Managers.BasePoiManager", "AddToWorld", false, "Behaviour.Unit.AbstractUnit", "Source.Data.AbstractUnitData", "System.String", "System.Boolean"),
        new("worldActiveUpdate", "Source.Galaxy.MapPointOfInterest", "ActiveUpdate", false, "System.Void", "System.Single"),
        new("worldCanTravel", "Source.Galaxy.MapPointOfInterest", "CanTravelHere", false, "System.Boolean"),
        new("worldRoute", BindingCatalog.TravelManager, "SetRouteToPOI", false, "System.Boolean", "Source.Galaxy.MapPointOfInterest"),
        new("worldCombatUpdate", "Source.Galaxy.POI.Combat", "AmbientUpdate", false, "System.Void", "System.Single")
    };
}
