<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.1</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VGModAPI.Abstractions/VGModAPI.Abstractions.csproj" />
    <InternalsVisibleTo Include="VGModAPI" />
    <InternalsVisibleTo Include="VGModAPI.Tests" />
  </ItemGroup>
</Project>
